/*
 * This source file was generated by the Gradle 'init' task
 */
package map;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class TreeMapTest {

  @Test
  void treemapHasInsert() {
    TreeMap map = new TreeMap();
    assertNotNull(map.insert("A", "B"), "TreeMap should have insert");
    map = new TreeMap();
    assertTrue(
      map.insert("A", "B"),
      "TreeMap insert has unexpected default behavior"
    );
    assertEquals(
      "[ \"A\" : \"B\" ]",
      map.toString(),
      "TreeMap insert has unexpected behavior"
    );
  }

  @Test
  void treemapHasDelete() {
    TreeMap map = new TreeMap();
    assertNotNull(map.delete("A"), "TreeMap should have delete");
    map = new TreeMap();
    map.insert("A", "B");
    assertTrue(
      map.delete("A"),
      "TreeMap delete has unexpected default behavior"
    );
    assertEquals(
      "null",
      map.toString(),
      "TreeMap delete has unexpected behavior"
    );
  }

  @Test
  void treemapHasSearch() {
    TreeMap map = new TreeMap();
    assertNotNull(map.search("A"), "TreeMap should have search");
    map = new TreeMap();
    assertFalse(
      map.search("A"),
      "TreeMap search has unexpected default behavior"
    );
    map.insert("A", "B");
    assertTrue(map.search("A"), "TreeMap search has unexpected behavior");
  }

  @Test
  void treemapHasGet() {
    TreeMap map = new TreeMap();
    assertNotNull(map.get("A"), "TreeMap should have get");
    map = new TreeMap();
    assertEquals(
      "null",
      map.get("A"),
      "TreeMap get has unexpected default behavior"
    );
    map.insert("A", "B");
    assertEquals("B", map.get("A"), "TreeMap get has unexpected behavior");
  }

  @Test
  void treemapHasHeight() {
    TreeMap map = new TreeMap();
    assertNotNull(map.height(), "TreeMap should have height");
    map = new TreeMap();
    assertEquals(
      -1,
      map.height(),
      "TreeMap height has unexpected default behavior"
    );
    map.insert("A", "B");
    assertEquals(0, map.height(), "TreeMap height has unexpected behavior");
  }

  @Test
  void treemapHasSize() {
    TreeMap map = new TreeMap();
    assertNotNull(map.size(), "TreeMap should have size");
    map = new TreeMap();
    assertEquals(0, map.size(), "TreeMap size has unexpected default behavior");
    map.insert("A", "B");
    assertEquals(1, map.size(), "TreeMap size has unexpected behavior");
  }
}
