/*
 * This source file was generated by the Gradle 'init' task
 */
package map;

public class App {

  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    TreeMap tree = new TreeMap();
    tree.insert("30", "30");
    tree.insert("20", "20");
    tree.insert("10", "10");
    System.out.println(tree);
    System.out.println(tree.get("20"));
    System.out.println(tree);
  }
}
